### ISSUE TITLE
Problem keys are incorrect

### ISSUE THREAD

**Issue by myst-6** [myst-6/ukoly#24]
The problem names should be in camel case in the content files. For example, in `/content/problems/bio2/index.tsx`, we have `brokersdoom: ...` as one of the keys. This should be `brokersDoom` instead.

Furthermore, the first two keys in `/content/problems/bio1/index.tsx` are wrong. It says `proto` and `dine`, but these should clearly be `integerStrings` and `parsingLists` respectively.

**Comment by myst-6** [comment]
actually, as @macaquedev suggested let's just make it an array.

**Comment by macaquedev** [comment]
I've done this, please see the new branch
