### ISSUE TITLE
Constraints missing in the abridged statements of some BIO2 problems.

### ISSUE THREAD

**Issue by myst-6** [myst-6/ukoly#6]
Note: I'm just talking about BIO2 problems here.

We should be consistent. Either include them, or don't. I personally think that we should include them. It saves people having to click off of the page to check the constraints, and it should be quick and easy for us to add them into our editorials.

What do you think? @vladimirfilip @macaquedev

**Comment by macaquedev** [comment]
I don't think there's any point adding constraints into our editorials if they don't influence the solution in any way. Also, people are still going to be solving the problems by opening the BIO website, and not from our website, and they can see the constraints are there...

**Comment by myst-6** [comment]
True. Then I need to remove the constraints from the problems where I've added them in, for consistency.
