### ISSUE TITLE
Website renders very weirdly when on half-screen size

### ISSUE THREAD

**Issue by macaquedev** [myst-6/ukoly#71]
![image](https://github.com/user-attachments/assets/e1d3f739-1314-4012-9a5f-f1d9a928a93e)
@myst-6 @vladimirfilip

**Comment by myst-6** [comment]
similar issue to mobile layout, but this is a bit more pressing... i'll work on this later today

**Comment by macaquedev** [comment]
nice - good luck on codeforces
